from PyQt5 import QtCore, QtGui, QtWidgets
import sudoku
import time
from PyQt5.QtCore import QThread, pyqtSignal
from PyQt5.QtWidgets import QMessageBox
import sudokulist
import webbrowser
import time

history = []


class thread(QThread):
    change_state = pyqtSignal(list, int)

    def get_speed(self, speed):
        self.speed = speed

    def run(self):
        for value in history:
            self.change_state.emit(value, 0)
            time.sleep(self.speed / 1000)
            self.change_state.emit(value, 1)


class Ui_Main_Window(object):

    def __init__(self, ques_number, speed):
        self.flag = 0
        self.temp_ques = sudokulist.question_list(ques_number)
        self.question_num = ques_number
        self.animate_speed = speed
        self.once = 0
        self.website = "https://github.com/Pratyush-exe"

    def setupUi(self, Main_Window):
        Main_Window.setObjectName("Main_Window")
        Main_Window.resize(494, 729)
        self.mainwindow = Main_Window
        self.centralwidget = QtWidgets.QWidget(Main_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 156, 381, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.L40 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L40.setFont(font)
        self.L40.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L40.setAlignment(QtCore.Qt.AlignCenter)
        self.L40.setObjectName("L40")
        self.gridLayout.addWidget(self.L40, 4, 0, 1, 1)
        self.L60 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L60.setFont(font)
        self.L60.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L60.setAlignment(QtCore.Qt.AlignCenter)
        self.L60.setObjectName("L60")
        self.gridLayout.addWidget(self.L60, 6, 0, 1, 1)
        self.L50 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L50.setFont(font)
        self.L50.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L50.setAlignment(QtCore.Qt.AlignCenter)
        self.L50.setObjectName("L50")
        self.gridLayout.addWidget(self.L50, 5, 0, 1, 1)
        self.L70 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L70.setFont(font)
        self.L70.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L70.setAlignment(QtCore.Qt.AlignCenter)
        self.L70.setObjectName("L70")
        self.gridLayout.addWidget(self.L70, 7, 0, 1, 1)
        self.L01 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L01.setFont(font)
        self.L01.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L01.setAlignment(QtCore.Qt.AlignCenter)
        self.L01.setObjectName("L01")
        self.gridLayout.addWidget(self.L01, 0, 1, 1, 1)
        self.L03 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L03.setFont(font)
        self.L03.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L03.setAlignment(QtCore.Qt.AlignCenter)
        self.L03.setObjectName("L03")
        self.gridLayout.addWidget(self.L03, 0, 3, 1, 1)
        self.L30 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L30.setFont(font)
        self.L30.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L30.setAlignment(QtCore.Qt.AlignCenter)
        self.L30.setObjectName("L30")
        self.gridLayout.addWidget(self.L30, 3, 0, 1, 1)
        self.L05 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L05.setFont(font)
        self.L05.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L05.setAlignment(QtCore.Qt.AlignCenter)
        self.L05.setObjectName("L05")
        self.gridLayout.addWidget(self.L05, 0, 5, 1, 1)
        self.L10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L10.setFont(font)
        self.L10.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L10.setAlignment(QtCore.Qt.AlignCenter)
        self.L10.setObjectName("L10")
        self.gridLayout.addWidget(self.L10, 1, 0, 1, 1)
        self.L07 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L07.setFont(font)
        self.L07.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L07.setAlignment(QtCore.Qt.AlignCenter)
        self.L07.setObjectName("L07")
        self.gridLayout.addWidget(self.L07, 0, 7, 1, 1)
        self.L02 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L02.setFont(font)
        self.L02.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L02.setAlignment(QtCore.Qt.AlignCenter)
        self.L02.setObjectName("L02")
        self.gridLayout.addWidget(self.L02, 0, 2, 1, 1)
        self.L00 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L00.setFont(font)
        self.L00.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L00.setAlignment(QtCore.Qt.AlignCenter)
        self.L00.setObjectName("L00")
        self.gridLayout.addWidget(self.L00, 0, 0, 1, 1)
        self.L04 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L04.setFont(font)
        self.L04.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L04.setAlignment(QtCore.Qt.AlignCenter)
        self.L04.setObjectName("L04")
        self.gridLayout.addWidget(self.L04, 0, 4, 1, 1)
        self.L08 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L08.setFont(font)
        self.L08.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L08.setAlignment(QtCore.Qt.AlignCenter)
        self.L08.setObjectName("L08")
        self.gridLayout.addWidget(self.L08, 0, 8, 1, 1)
        self.L06 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L06.setFont(font)
        self.L06.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L06.setAlignment(QtCore.Qt.AlignCenter)
        self.L06.setObjectName("L06")
        self.gridLayout.addWidget(self.L06, 0, 6, 1, 1)
        self.L20 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L20.setFont(font)
        self.L20.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L20.setAlignment(QtCore.Qt.AlignCenter)
        self.L20.setObjectName("L20")
        self.gridLayout.addWidget(self.L20, 2, 0, 1, 1)
        self.L80 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L80.setFont(font)
        self.L80.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L80.setAlignment(QtCore.Qt.AlignCenter)
        self.L80.setObjectName("L80")
        self.gridLayout.addWidget(self.L80, 8, 0, 1, 1)
        self.L11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L11.setFont(font)
        self.L11.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L11.setAlignment(QtCore.Qt.AlignCenter)
        self.L11.setObjectName("L11")
        self.gridLayout.addWidget(self.L11, 1, 1, 1, 1)
        self.L12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L12.setFont(font)
        self.L12.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L12.setAlignment(QtCore.Qt.AlignCenter)
        self.L12.setObjectName("L12")
        self.gridLayout.addWidget(self.L12, 1, 2, 1, 1)
        self.L21 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L21.setFont(font)
        self.L21.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L21.setAlignment(QtCore.Qt.AlignCenter)
        self.L21.setObjectName("L21")
        self.gridLayout.addWidget(self.L21, 2, 1, 1, 1)
        self.L31 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L31.setFont(font)
        self.L31.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L31.setAlignment(QtCore.Qt.AlignCenter)
        self.L31.setObjectName("L31")
        self.gridLayout.addWidget(self.L31, 3, 1, 1, 1)
        self.L41 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L41.setFont(font)
        self.L41.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L41.setAlignment(QtCore.Qt.AlignCenter)
        self.L41.setObjectName("L41")
        self.gridLayout.addWidget(self.L41, 4, 1, 1, 1)
        self.L51 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L51.setFont(font)
        self.L51.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L51.setAlignment(QtCore.Qt.AlignCenter)
        self.L51.setObjectName("L51")
        self.gridLayout.addWidget(self.L51, 5, 1, 1, 1)
        self.L61 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L61.setFont(font)
        self.L61.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L61.setAlignment(QtCore.Qt.AlignCenter)
        self.L61.setObjectName("L61")
        self.gridLayout.addWidget(self.L61, 6, 1, 1, 1)
        self.L71 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L71.setFont(font)
        self.L71.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L71.setAlignment(QtCore.Qt.AlignCenter)
        self.L71.setObjectName("L71")
        self.gridLayout.addWidget(self.L71, 7, 1, 1, 1)
        self.L81 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L81.setFont(font)
        self.L81.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L81.setAlignment(QtCore.Qt.AlignCenter)
        self.L81.setObjectName("L81")
        self.gridLayout.addWidget(self.L81, 8, 1, 1, 1)
        self.L13 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L13.setFont(font)
        self.L13.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L13.setAlignment(QtCore.Qt.AlignCenter)
        self.L13.setObjectName("L13")
        self.gridLayout.addWidget(self.L13, 1, 3, 1, 1)
        self.L14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L14.setFont(font)
        self.L14.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L14.setAlignment(QtCore.Qt.AlignCenter)
        self.L14.setObjectName("L14")
        self.gridLayout.addWidget(self.L14, 1, 4, 1, 1)
        self.L22 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L22.setFont(font)
        self.L22.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L22.setAlignment(QtCore.Qt.AlignCenter)
        self.L22.setObjectName("L22")
        self.gridLayout.addWidget(self.L22, 2, 2, 1, 1)
        self.L23 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L23.setFont(font)
        self.L23.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L23.setAlignment(QtCore.Qt.AlignCenter)
        self.L23.setObjectName("L23")
        self.gridLayout.addWidget(self.L23, 2, 3, 1, 1)
        self.L24 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L24.setFont(font)
        self.L24.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L24.setAlignment(QtCore.Qt.AlignCenter)
        self.L24.setObjectName("L24")
        self.gridLayout.addWidget(self.L24, 2, 4, 1, 1)
        self.L15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L15.setFont(font)
        self.L15.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L15.setAlignment(QtCore.Qt.AlignCenter)
        self.L15.setObjectName("L15")
        self.gridLayout.addWidget(self.L15, 1, 5, 1, 1)
        self.L16 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L16.setFont(font)
        self.L16.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L16.setAlignment(QtCore.Qt.AlignCenter)
        self.L16.setObjectName("L16")
        self.gridLayout.addWidget(self.L16, 1, 6, 1, 1)
        self.L17 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L17.setFont(font)
        self.L17.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L17.setAlignment(QtCore.Qt.AlignCenter)
        self.L17.setObjectName("L17")
        self.gridLayout.addWidget(self.L17, 1, 7, 1, 1)
        self.L18 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L18.setFont(font)
        self.L18.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L18.setAlignment(QtCore.Qt.AlignCenter)
        self.L18.setObjectName("L18")
        self.gridLayout.addWidget(self.L18, 1, 8, 1, 1)
        self.L25 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L25.setFont(font)
        self.L25.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L25.setAlignment(QtCore.Qt.AlignCenter)
        self.L25.setObjectName("L25")
        self.gridLayout.addWidget(self.L25, 2, 5, 1, 1)
        self.L26 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L26.setFont(font)
        self.L26.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L26.setAlignment(QtCore.Qt.AlignCenter)
        self.L26.setObjectName("L26")
        self.gridLayout.addWidget(self.L26, 2, 6, 1, 1)
        self.L27 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L27.setFont(font)
        self.L27.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L27.setAlignment(QtCore.Qt.AlignCenter)
        self.L27.setObjectName("L27")
        self.gridLayout.addWidget(self.L27, 2, 7, 1, 1)
        self.L28 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L28.setFont(font)
        self.L28.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L28.setAlignment(QtCore.Qt.AlignCenter)
        self.L28.setObjectName("L28")
        self.gridLayout.addWidget(self.L28, 2, 8, 1, 1)
        self.L32 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L32.setFont(font)
        self.L32.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L32.setAlignment(QtCore.Qt.AlignCenter)
        self.L32.setObjectName("L32")
        self.gridLayout.addWidget(self.L32, 3, 2, 1, 1)
        self.L42 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L42.setFont(font)
        self.L42.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L42.setAlignment(QtCore.Qt.AlignCenter)
        self.L42.setObjectName("L42")
        self.gridLayout.addWidget(self.L42, 4, 2, 1, 1)
        self.L52 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L52.setFont(font)
        self.L52.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L52.setAlignment(QtCore.Qt.AlignCenter)
        self.L52.setObjectName("L52")
        self.gridLayout.addWidget(self.L52, 5, 2, 1, 1)
        self.L62 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L62.setFont(font)
        self.L62.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L62.setAlignment(QtCore.Qt.AlignCenter)
        self.L62.setObjectName("L62")
        self.gridLayout.addWidget(self.L62, 6, 2, 1, 1)
        self.L72 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L72.setFont(font)
        self.L72.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L72.setAlignment(QtCore.Qt.AlignCenter)
        self.L72.setObjectName("L72")
        self.gridLayout.addWidget(self.L72, 7, 2, 1, 1)
        self.L82 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L82.setFont(font)
        self.L82.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L82.setAlignment(QtCore.Qt.AlignCenter)
        self.L82.setObjectName("L82")
        self.gridLayout.addWidget(self.L82, 8, 2, 1, 1)
        self.L33 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L33.setFont(font)
        self.L33.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L33.setAlignment(QtCore.Qt.AlignCenter)
        self.L33.setObjectName("L33")
        self.gridLayout.addWidget(self.L33, 3, 3, 1, 1)
        self.L34 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L34.setFont(font)
        self.L34.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L34.setAlignment(QtCore.Qt.AlignCenter)
        self.L34.setObjectName("L34")
        self.gridLayout.addWidget(self.L34, 3, 4, 1, 1)
        self.L43 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L43.setFont(font)
        self.L43.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L43.setAlignment(QtCore.Qt.AlignCenter)
        self.L43.setObjectName("L43")
        self.gridLayout.addWidget(self.L43, 4, 3, 1, 1)
        self.L53 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L53.setFont(font)
        self.L53.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L53.setAlignment(QtCore.Qt.AlignCenter)
        self.L53.setObjectName("L53")
        self.gridLayout.addWidget(self.L53, 5, 3, 1, 1)
        self.L63 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L63.setFont(font)
        self.L63.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L63.setAlignment(QtCore.Qt.AlignCenter)
        self.L63.setObjectName("L63")
        self.gridLayout.addWidget(self.L63, 6, 3, 1, 1)
        self.L73 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L73.setFont(font)
        self.L73.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L73.setAlignment(QtCore.Qt.AlignCenter)
        self.L73.setObjectName("L73")
        self.gridLayout.addWidget(self.L73, 7, 3, 1, 1)
        self.L83 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L83.setFont(font)
        self.L83.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L83.setAlignment(QtCore.Qt.AlignCenter)
        self.L83.setObjectName("L83")
        self.gridLayout.addWidget(self.L83, 8, 3, 1, 1)
        self.L44 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L44.setFont(font)
        self.L44.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L44.setAlignment(QtCore.Qt.AlignCenter)
        self.L44.setObjectName("L44")
        self.gridLayout.addWidget(self.L44, 4, 4, 1, 1)
        self.L54 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L54.setFont(font)
        self.L54.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L54.setAlignment(QtCore.Qt.AlignCenter)
        self.L54.setObjectName("L54")
        self.gridLayout.addWidget(self.L54, 5, 4, 1, 1)
        self.L64 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L64.setFont(font)
        self.L64.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L64.setAlignment(QtCore.Qt.AlignCenter)
        self.L64.setObjectName("L64")
        self.gridLayout.addWidget(self.L64, 6, 4, 1, 1)
        self.L74 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L74.setFont(font)
        self.L74.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L74.setAlignment(QtCore.Qt.AlignCenter)
        self.L74.setObjectName("L74")
        self.gridLayout.addWidget(self.L74, 7, 4, 1, 1)
        self.L84 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L84.setFont(font)
        self.L84.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L84.setAlignment(QtCore.Qt.AlignCenter)
        self.L84.setObjectName("L84")
        self.gridLayout.addWidget(self.L84, 8, 4, 1, 1)
        self.L35 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L35.setFont(font)
        self.L35.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L35.setAlignment(QtCore.Qt.AlignCenter)
        self.L35.setObjectName("L35")
        self.gridLayout.addWidget(self.L35, 3, 5, 1, 1)
        self.L45 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L45.setFont(font)
        self.L45.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L45.setAlignment(QtCore.Qt.AlignCenter)
        self.L45.setObjectName("L45")
        self.gridLayout.addWidget(self.L45, 4, 5, 1, 1)
        self.L55 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L55.setFont(font)
        self.L55.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L55.setAlignment(QtCore.Qt.AlignCenter)
        self.L55.setObjectName("L55")
        self.gridLayout.addWidget(self.L55, 5, 5, 1, 1)
        self.L65 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L65.setFont(font)
        self.L65.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L65.setAlignment(QtCore.Qt.AlignCenter)
        self.L65.setObjectName("L65")
        self.gridLayout.addWidget(self.L65, 6, 5, 1, 1)
        self.L75 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L75.setFont(font)
        self.L75.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L75.setAlignment(QtCore.Qt.AlignCenter)
        self.L75.setObjectName("L75")
        self.gridLayout.addWidget(self.L75, 7, 5, 1, 1)
        self.L85 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L85.setFont(font)
        self.L85.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L85.setAlignment(QtCore.Qt.AlignCenter)
        self.L85.setObjectName("L85")
        self.gridLayout.addWidget(self.L85, 8, 5, 1, 1)
        self.L36 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L36.setFont(font)
        self.L36.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L36.setAlignment(QtCore.Qt.AlignCenter)
        self.L36.setObjectName("L36")
        self.gridLayout.addWidget(self.L36, 3, 6, 1, 1)
        self.L37 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L37.setFont(font)
        self.L37.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L37.setAlignment(QtCore.Qt.AlignCenter)
        self.L37.setObjectName("L37")
        self.gridLayout.addWidget(self.L37, 3, 7, 1, 1)
        self.L46 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L46.setFont(font)
        self.L46.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L46.setAlignment(QtCore.Qt.AlignCenter)
        self.L46.setObjectName("L46")
        self.gridLayout.addWidget(self.L46, 4, 6, 1, 1)
        self.L47 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L47.setFont(font)
        self.L47.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L47.setAlignment(QtCore.Qt.AlignCenter)
        self.L47.setObjectName("L47")
        self.gridLayout.addWidget(self.L47, 4, 7, 1, 1)
        self.L56 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L56.setFont(font)
        self.L56.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L56.setAlignment(QtCore.Qt.AlignCenter)
        self.L56.setObjectName("L56")
        self.gridLayout.addWidget(self.L56, 5, 6, 1, 1)
        self.L57 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L57.setFont(font)
        self.L57.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L57.setAlignment(QtCore.Qt.AlignCenter)
        self.L57.setObjectName("L57")
        self.gridLayout.addWidget(self.L57, 5, 7, 1, 1)
        self.L66 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L66.setFont(font)
        self.L66.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L66.setAlignment(QtCore.Qt.AlignCenter)
        self.L66.setObjectName("L66")
        self.gridLayout.addWidget(self.L66, 6, 6, 1, 1)
        self.L67 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L67.setFont(font)
        self.L67.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L67.setAlignment(QtCore.Qt.AlignCenter)
        self.L67.setObjectName("L67")
        self.gridLayout.addWidget(self.L67, 6, 7, 1, 1)
        self.L76 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L76.setFont(font)
        self.L76.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L76.setAlignment(QtCore.Qt.AlignCenter)
        self.L76.setObjectName("L76")
        self.gridLayout.addWidget(self.L76, 7, 6, 1, 1)
        self.L77 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L77.setFont(font)
        self.L77.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L77.setAlignment(QtCore.Qt.AlignCenter)
        self.L77.setObjectName("L77")
        self.gridLayout.addWidget(self.L77, 7, 7, 1, 1)
        self.L86 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L86.setFont(font)
        self.L86.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L86.setAlignment(QtCore.Qt.AlignCenter)
        self.L86.setObjectName("L86")
        self.gridLayout.addWidget(self.L86, 8, 6, 1, 1)
        self.L87 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L87.setFont(font)
        self.L87.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L87.setAlignment(QtCore.Qt.AlignCenter)
        self.L87.setObjectName("L87")
        self.gridLayout.addWidget(self.L87, 8, 7, 1, 1)
        self.L88 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L88.setFont(font)
        self.L88.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L88.setAlignment(QtCore.Qt.AlignCenter)
        self.L88.setObjectName("L88")
        self.gridLayout.addWidget(self.L88, 8, 8, 1, 1)
        self.L78 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L78.setFont(font)
        self.L78.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L78.setAlignment(QtCore.Qt.AlignCenter)
        self.L78.setObjectName("L78")
        self.gridLayout.addWidget(self.L78, 7, 8, 1, 1)
        self.L68 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L68.setFont(font)
        self.L68.setStyleSheet("background-color: rgb(150, 150, 150);\n"
                               "border-radius: 8px;")
        self.L68.setAlignment(QtCore.Qt.AlignCenter)
        self.L68.setObjectName("L68")
        self.gridLayout.addWidget(self.L68, 6, 8, 1, 1)
        self.L58 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L58.setFont(font)
        self.L58.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L58.setAlignment(QtCore.Qt.AlignCenter)
        self.L58.setObjectName("L58")
        self.gridLayout.addWidget(self.L58, 5, 8, 1, 1)
        self.L48 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L48.setFont(font)
        self.L48.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L48.setAlignment(QtCore.Qt.AlignCenter)
        self.L48.setObjectName("L48")
        self.gridLayout.addWidget(self.L48, 4, 8, 1, 1)
        self.L38 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L38.setFont(font)
        self.L38.setStyleSheet("background-color: rgb(221, 221, 221);\n"
                               "border-radius: 8px;")
        self.L38.setAlignment(QtCore.Qt.AlignCenter)
        self.L38.setObjectName("L38")
        self.gridLayout.addWidget(self.L38, 3, 8, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.centralwidget)
        self.label_82.setGeometry(QtCore.QRect(-7, -4, 521, 821))
        self.label_82.setStyleSheet("background-color: rgb(79, 79, 79);")
        self.label_82.setText("")
        self.label_82.setObjectName("label_82")
        self.solve = QtWidgets.QLabel(self.centralwidget)
        self.solve.setGeometry(QtCore.QRect(53, 650, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.solve.setFont(font)
        self.solve.setStyleSheet("background-color: rgb(255, 242, 0);\n"
                                 "border-radius: 20px;\n"
                                 "color: rgb(79, 79, 79);")
        self.solve.setAlignment(QtCore.Qt.AlignCenter)
        self.solve.setObjectName("solve")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(123, 26, 251, 71))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(r"images\sudoku.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.solve_shadow = QtWidgets.QLabel(self.centralwidget)
        self.solve_shadow.setGeometry(QtCore.QRect(56, 656, 401, 41))
        self.solve_shadow.setStyleSheet("background-color: rgb(251, 207, 0);\n"
                                        "border-radius: 20px;")
        self.solve_shadow.setObjectName("solve_shadow")
        self.new_ques_button_shadow = QtWidgets.QLabel(self.centralwidget)
        self.new_ques_button_shadow.setGeometry(QtCore.QRect(56, 591, 191, 41))
        self.new_ques_button_shadow.setStyleSheet("background-color: rgb(251, 207, 0);\n"
                                                  "border-radius: 20px;")
        self.new_ques_button_shadow.setObjectName("new_ques_button_shadow")
        self.new_ques_button = QtWidgets.QPushButton(self.centralwidget)
        self.new_ques_button.setGeometry(QtCore.QRect(53, 586, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.new_ques_button.setFont(font)
        self.new_ques_button.setStyleSheet("background-color: rgb(255, 242, 0);\n"
                                           "border-radius: 20px;\n"
                                           "color: rgb(79, 79, 79);")
        # self.new_ques_button.setAlignment(QtCore.Qt.AlignCenter)
        self.new_ques_button.setObjectName("new_ques_button")
        self.about_shadow = QtWidgets.QLabel(self.centralwidget)
        self.about_shadow.setGeometry(QtCore.QRect(276, 591, 181, 41))
        self.about_shadow.setStyleSheet("background-color: rgb(251, 207, 0);\n"
                                        "border-radius: 20px;")
        self.about_shadow.setText("")
        self.about_shadow.setObjectName("about_shadow")
        self.about_button = QtWidgets.QPushButton(self.centralwidget)
        self.about_button.setGeometry(QtCore.QRect(273, 586, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.about_button.setFont(font)
        self.about_button.setStyleSheet("background-color: rgb(255, 242, 0);\n"
                                        "border-radius: 20px;\n"
                                        "color: rgb(79, 79, 79);")
        self.about_button.setObjectName("about_button")
        self.label_82.raise_()
        self.gridLayoutWidget.raise_()
        self.logo.raise_()
        self.solve_shadow.raise_()
        self.solve.raise_()
        self.new_ques_button_shadow.raise_()
        self.new_ques_button.raise_()
        self.about_shadow.raise_()
        self.about_button.raise_()
        Main_Window.setCentralWidget(self.centralwidget)

        self.L = [[self.L00, self.L01, self.L02, self.L03, self.L04, self.L05, self.L06, self.L07, self.L08, ],

                  [self.L10, self.L11, self.L12, self.L13, self.L14, self.L15, self.L16, self.L17, self.L18, ],

                  [self.L20, self.L21, self.L22, self.L23, self.L24, self.L25, self.L26, self.L27, self.L28, ],

                  [self.L30, self.L31, self.L32, self.L33, self.L34, self.L35, self.L36, self.L37, self.L38, ],

                  [self.L40, self.L41, self.L42, self.L43, self.L44, self.L45, self.L46, self.L47, self.L48, ],

                  [self.L50, self.L51, self.L52, self.L53, self.L54, self.L55, self.L56, self.L57, self.L58, ],

                  [self.L60, self.L61, self.L62, self.L63, self.L64, self.L65, self.L66, self.L67, self.L68, ],

                  [self.L70, self.L71, self.L72, self.L73, self.L74, self.L75, self.L76, self.L77, self.L78, ],

                  [self.L80, self.L81, self.L82, self.L83, self.L84, self.L85, self.L86, self.L87, self.L88, ]]

        self.new_ques_button.clicked.connect(lambda: self.mainwindow.close())
        self.solve.mousePressEvent = self.solve_board
        self.about_button.clicked.connect(lambda: webbrowser.open_new(self.website))

        self.retranslateUi(Main_Window)
        QtCore.QMetaObject.connectSlotsByName(Main_Window)

    def open_git(self, _):
        webbrowser.open_new(self.website)

    def restart(self):
        self.mainwindow.close()

    def start_viz(self):
        self.thread = thread()
        self.thread.change_state.connect(self.setvalue)
        self.thread.get_speed(self.animate_speed)
        self.thread.start()

    def setvalue(self, val, border):
        if border == 0:
            if (0 <= val[1] <= 2 and 3 <= val[2] <= 5) or (3 <= val[1] <= 5 and 0 <= val[2] <= 2) or (
                    3 <= val[1] <= 5 and 6 <= val[2] <= 8) or (6 <= val[1] <= 8 and 3 <= val[2] <= 5):

                self.L[val[1]][val[2]].setStyleSheet("background-color: rgb(221, 221, 221);\n"
                                                     "border-radius: 8px;"
                                                     "border: 2px solid red;"
                                                     "color:red;")
                self.L[val[1]][val[2]].setText(str(val[0]))
            else:

                self.L[val[1]][val[2]].setStyleSheet("background-color: rgb(150, 150, 150);\n"
                                                     "border-radius: 8px;"
                                                     "border: 2px solid red;"
                                                     "color:red;")
                self.L[val[1]][val[2]].setText(str(val[0]))
        elif border == 1:
            if (0 <= val[1] <= 2 and 3 <= val[2] <= 5) or (3 <= val[1] <= 5 and 0 <= val[2] <= 2) or (
                    3 <= val[1] <= 5 and 6 <= val[2] <= 8) or (6 <= val[1] <= 8 and 3 <= val[2] <= 5):
                self.L[val[1]][val[2]].setStyleSheet("background-color: rgb(221, 221, 221);\n"
                                                     "border-radius: 8px;"
                                                     "color:black;")
            else:
                self.L[val[1]][val[2]].setStyleSheet("background-color: rgb(150, 150, 150);\n"
                                                     "border-radius: 8px;"
                                                     "color:black")

    def solve_func(self, _):
        find = sudoku.find_empty(self.temp_ques)
        if not find:
            return True
        else:
            row, col = find
        for i in range(1, 10):
            if sudoku.valid(self.temp_ques, i, (row, col)):
                self.temp_ques[row][col] = i
                history.append([i, row, col])
                if self.solve_func(self.temp_ques):
                    return True
                self.temp_ques[row][col] = 0
        return False

    def solve_board(self, _):

        if self.once == 0:
            self.once = 1

            init_timer = time.process_time()
            self.solve_func(0)
            final_timer = time.process_time()
            print("\nSolved in ", final_timer - init_timer, "seconds: ")
            sudoku.print_board(self.temp_ques)
            self.start_viz()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("sudoku")
            msg.setIcon(QMessageBox.Warning)
            msg.setText("    Already Clicked!")
            msg.exec_()

    def new_ques(self):

        ques_temp = sudokulist.question_list(self.question_num)
        for i in range(9):
            for j in range(9):
                if ques_temp[i][j] == 0:
                    self.L[i][j].setText("")
                    ques_temp[i][j] = 0
                else:
                    self.L[i][j].setText(str(ques_temp[i][j]))
                    ques_temp[i][j] = 0
        self.flag = 1

    def retranslateUi(self, Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Main_Window.setWindowTitle(_translate("Main_Window", "sudoku"))
        Main_Window.setWindowIcon(QtGui.QIcon(r"images\icon.ico"))
        self.solve.setText(_translate("Main_Window", "Solved"))
        _ = ""
        self.new_ques()
        self.solve_shadow.setText(_translate("Main_Window", "TextLabel"))
        self.new_ques_button_shadow.setText(_translate("Main_Window", "TextLabel"))
        self.new_ques_button.setText(_translate("Main_Window", "New Question"))
        self.about_button.setText(_translate("Main_Window", "About"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Main_Window = QtWidgets.QMainWindow()
    ui = Ui_Main_Window()
    ui.setupUi(Main_Window)
    Main_Window.show()
    sys.exit(app.exec_())
